# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

# Required by RNFirebase
pod 'Firebase/Core', '~> 5.15.0'
pod 'Firebase/Auth', '~> 5.15.0'

target 'SquidSpace' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SquidSpace

  target 'SquidSpace-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SquidSpaceTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SquidSpace-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SquidSpace-tvOS

end
